In [73]:
import pandas as pd
import numpy as np

adv_df = pd.read_csv("Advertising.csv")

In [74]:
adv_df

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [75]:
from sklearn.model_selection import train_test_split

In [76]:
train_data, test_data = train_test_split(adv_df, test_size=0.2,random_state=32)

In [77]:
test_data

        TV  radio  newspaper  sales
122  224.0    2.4       15.6   11.6
186  139.5    2.1       26.6   10.3
167  206.8    5.2       19.4   12.2
101  296.4   36.3      100.9   23.8
29    70.6   16.0       40.8   10.5
75    16.9   43.7       89.4    8.7
144   96.2   14.8       38.9   11.4
28   248.8   27.1       22.9   18.9
121   18.8   21.7       50.4    7.0
182   56.2    5.7       29.7    8.7
27   240.1   16.7       22.9   15.9
181  218.5    5.4       27.4   12.2
39   228.0   37.7       32.0   21.5
23   228.3   16.9       26.2   15.5
2     17.2   45.9       69.3    9.3
173  168.4    7.1       12.8   11.7
107   90.4    0.3       23.2    8.7
17   281.4   39.6       55.8   24.4
109  255.4   26.9        5.5   19.8
118  125.7   36.9       79.2   15.9
26   142.9   29.3       12.6   15.0
46    89.7    9.9       35.7   10.6
21   237.4    5.1       23.5   12.5
160  172.5   18.1       30.7   14.4
44    25.1   25.7       43.3    8.5
143  104.6    5.7       34.4   10.4
56     7.3   28.1       41.4    5.5
188  286.0   13.9        3.7   15.9
79   116.0    7.7       23.1   11.0
73   129.4    5.7       31.3   11.0
164  117.2   14.7        5.4   11.9
18    69.2   20.5       18.3   11.3
102  280.2   10.1       21.4   14.8
131  265.2    2.9       43.0   12.7
96   197.6    3.5        5.9   11.7
141  193.7   35.4       75.6   19.2
115   75.1   35.0       52.7   12.6
174  222.4    3.4       13.1   11.5
130    0.7   39.6        8.7    1.6
34    95.7    1.4        7.4    9.5

In [78]:
train_data

        TV  radio  newspaper  sales
156   93.9   43.5       50.5   15.3
154  187.8   21.1        9.5   15.6
153  171.3   39.7       37.7   19.0
197  177.0    9.3        6.4   12.8
185  205.0   45.1       19.6   22.6
..     ...    ...        ...    ...
190   39.5   41.1        5.8   10.8
124  229.5   32.3       74.2   19.7
54   262.7   28.8       15.9   20.2
133  219.8   33.5       45.1   19.6
43   206.9    8.4       26.4   12.9

[160 rows x 4 columns]

In [79]:
X_train = train_data.drop("sales",axis = 1)
y_train = train_data["sales"]
X_test = test_data.drop("sales", axis = 1)
y_test = test_data["sales"]

In [80]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error

In [81]:
MLR = LinearRegression()

In [82]:
#fit the data
#Predict the y_test 
#Use RootMeanSquaredError 
MLR.fit(X_train,y_train)

LinearRegression()

In [83]:
y_pred = MLR.predict(X_test)

In [84]:
MLR.coef_

array([ 0.04571871,  0.19323161, -0.00317112])

In [85]:
root_mean_squared_error(y_pred,y_test)

2.1777843359613525