In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("EEG-Eye-State.csv")

df

,AF3,AF4,F3,F4,F7,F8,FC5,FC6,T7,T8,P7,P8,O1,O2,eyeDetection
0,4329.23,4393.85,4289.23,4280.51,4009.23,4635.90,4148.21,4211.28,4350.26,4238.46,4586.15,4222.05,4096.92,4641.03,0
1,4324.62,4384.10,4293.85,4279.49,4004.62,4632.82,4148.72,4207.69,4342.05,4226.67,4586.67,4210.77,4097.44,4638.97,0
2,4327.69,4389.23,4295.38,4282.05,4006.67,4628.72,4156.41,4206.67,4336.92,4222.05,4583.59,4207.69,4096.92,4630.26,0
3,4328.72,4396.41,4296.41,4287.69,4011.79,4632.31,4155.90,4210.77,4343.59,4235.38,4582.56,4217.44,4097.44,4630.77,0
4,4326.15,4398.46,4292.31,4288.21,4011.79,4632.82,4151.28,4212.82,4347.69,4244.10,4586.67,4210.77,4095.90,4627.69,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14975,4281.03,4340.51,4245.64,4269.23,3990.26,4593.33,4116.92,4171.28,4333.85,4221.54,4614.36,4203.08,4074.87,4625.64,1
14976,4276.92,4333.33,4245.13,4259.49,3991.79,4590.26,4110.77,4162.56,4332.82,4217.44,4615.38,4194.36,4073.33,4621.54,1
14977,4277.44,4339.49,4246.67,4257.95,3990.77,4591.79,4113.85,4160.51,4333.33,4212.82,4615.38,4193.33,4072.82,4623.59,1
14978,4284.62,4350.77,4251.28,4267.18,3991.79,4596.41,4122.05,4165.64,4334.36,4220.00,4616.41,4200.00,4080.51,4628.72,1
14979,4287.69,4350.77,4260.00,4274.36,3997.44,4597.95,4121.03,4167.69,4333.33,4226.67,4616.41,4212.31,4088.72,4638.46,1

In [2]:
df.columns

Index(['AF3', 'AF4', 'F3', 'F4', 'F7', 'F8', 'FC5', 'FC6', 'T7', 'T8', 'P7',
       'P8', 'O1', 'O2', 'eyeDetection'],
      dtype='str')

In [3]:
df.isna().sum()

AF3             0
AF4             0
F3              0
F4              0
F7              0
F8              0
FC5             0
FC6             0
T7              0
T8              0
P7              0
P8              0
O1              0
O2              0
eyeDetection    0
dtype: int64

In [4]:
df.describe()

,AF3,AF4,F3,F4,F7,F8,FC5,FC6,T7,T8,P7,P8,O1,O2,eyeDetection
count,14980.000000,14980.000000,14980.000000,14980.000000,14980.000000,14980.000000,14980.000000,14980.000000,14980.000000,14980.000000,14980.000000,14980.000000,14980.000000,14980.000000,14980.000000
mean,4321.917777,4416.435832,4264.022433,4279.232774,4009.767694,4615.205336,4164.946326,4202.456900,4341.741075,4231.316200,4644.022379,4218.826610,4110.400160,4616.056904,0.448798
std,2492.072174,5891.285043,44.428052,41.544312,45.941672,1208.369958,5216.404632,37.785981,34.738821,38.050903,2924.789537,2136.408523,4600.926543,29.292603,0.497388
min,1030.770000,1366.150000,1040.000000,2257.950000,2830.770000,86.666700,2453.330000,3273.330000,2089.740000,1816.410000,2768.210000,1357.950000,2086.150000,4567.180000,0.000000
25%,4280.510000,4342.050000,4250.260000,4267.690000,3990.770000,4590.770000,4108.210000,4190.260000,4331.790000,4220.510000,4611.790000,4190.770000,4057.950000,4604.620000,0.000000
50%,4294.360000,4354.870000,4262.560000,4276.920000,4005.640000,4603.080000,4120.510000,4200.510000,4338.970000,4229.230000,4617.950000,4199.490000,4070.260000,4613.330000,0.000000
75%,4311.790000,4372.820000,4270.770000,4287.180000,4023.080000,4617.440000,4132.310000,4211.280000,4347.180000,4239.490000,4626.670000,4209.230000,4083.590000,4624.100000,1.000000
max,309231.000000,715897.000000,6880.510000,7002.560000,7804.620000,152308.000000,642564.000000,6823.080000,6474.360000,6674.360000,362564.000000,265641.000000,567179.000000,7264.100000,1.000000

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
train_data, test_data = train_test_split(df, test_size=0.2,random_state=32)

In [7]:
test_data

,AF3,AF4,F3,F4,F7,F8,FC5,FC6,T7,T8,P7,P8,O1,O2,eyeDetection
4158,4277.44,4334.36,4246.15,4270.77,3991.79,4609.23,4119.49,4197.44,4327.69,4215.38,4622.05,4197.95,4052.82,4605.64,1
7403,4308.21,4376.92,4274.87,4295.90,4001.54,4617.95,4127.18,4198.46,4321.03,4232.31,4620.51,4206.15,4078.46,4618.46,1
1344,4355.90,4450.26,4275.38,4310.77,3985.13,4700.00,4103.08,4257.95,4326.67,4249.74,4591.79,4222.56,4084.10,4619.49,1
634,4333.33,4389.23,4277.44,4298.97,4055.90,4638.97,4122.56,4234.87,4352.31,4244.62,4634.36,4223.59,4113.85,4627.18,1
4236,4282.05,4340.51,4264.62,4283.08,3980.51,4577.44,4108.72,4176.92,4311.28,4200.51,4604.62,4183.08,4056.92,4606.15,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7514,4312.82,4366.67,4278.97,4281.54,4015.38,4609.74,4129.74,4203.08,4341.03,4235.90,4623.59,4202.56,4072.31,4621.03,1
6851,4285.13,4341.54,4248.72,4269.23,3981.54,4575.38,4114.36,4191.79,4344.62,4234.36,4618.97,4223.08,4061.03,4628.72,1
7331,4309.74,4367.69,4278.97,4292.31,4015.38,4615.38,4154.36,4219.49,4335.90,4236.41,4608.21,4194.87,4043.08,4606.67,1
10428,4297.95,4342.05,4269.74,4275.90,3989.74,4587.18,4140.51,4196.41,4340.00,4220.00,4631.28,4202.05,4058.46,4613.85,0
9969,4302.05,4357.44,4274.36,4263.59,4011.79,4593.33,4119.49,4151.79,4341.03,4223.08,4615.90,4200.51,4052.82,4615.38,0

In [8]:
train_data

,AF3,AF4,F3,F4,F7,F8,FC5,FC6,T7,T8,P7,P8,O1,O2,eyeDetection
12308,4300.00,4360.51,4265.64,4287.18,4003.08,4632.82,4132.31,4223.59,4356.41,4247.69,4630.77,4217.95,4087.18,4649.23,0
12085,4271.28,4316.41,4281.03,4278.97,4051.79,4597.44,4168.72,4195.38,4390.26,4228.72,4650.77,4208.72,4094.87,4630.77,0
10357,4290.26,4342.05,4258.46,4269.23,3940.00,4597.95,4116.41,4209.74,4346.67,4231.79,4629.74,4213.85,4063.08,4613.85,0
2444,4307.18,4372.31,4246.67,4270.26,4006.15,4604.10,4112.31,4191.79,4326.15,4227.18,4597.95,4197.44,4056.92,4597.44,1
1407,4286.15,4389.74,4250.26,4285.13,3949.74,4636.92,4076.41,4223.08,4323.08,4241.03,4603.59,4219.49,4093.85,4630.26,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4030,4280.00,4334.87,4249.74,4260.00,4004.10,4598.46,4106.67,4190.77,4326.67,4215.90,4609.23,4185.13,4041.54,4599.49,1
11132,4349.23,4447.18,4294.36,4308.72,3993.33,4694.87,4122.05,4253.85,4358.97,4263.08,4633.85,4218.97,4090.77,4640.51,1
9526,4306.15,4364.10,4261.03,4269.74,3996.41,4598.46,4107.18,4208.21,4338.46,4228.21,4626.15,4200.51,4060.00,4614.36,0
9771,4290.77,4355.38,4277.95,4273.85,3992.82,4594.36,4123.08,4196.41,4336.41,4235.38,4604.62,4189.23,4045.13,4605.64,0
10967,4316.41,4386.15,4286.67,4293.33,4013.85,4617.95,4134.36,4222.05,4346.15,4241.54,4636.41,4197.44,4088.72,4631.28,0

In [9]:
X_train = train_data.drop("eyeDetection",axis = 1)
y_train = train_data["eyeDetection"]
X_test = test_data.drop("eyeDetection", axis = 1)
y_test = test_data["eyeDetection"]