In [30]:
import math
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import make_moons
from sklearn.cluster import KMeans, DBSCAN
import pandas as pd
import plotly.express as px

In [47]:
X_moons, _ = make_moons(500, noise=0.05, random_state=32)

In [48]:
px.scatter(pd.DataFrame({"x": X_moons[:, 0], "y": X_moons[:, 1]}), x="x", y="y", title="Moon Dataset")

In [49]:
kmeans = KMeans(n_clusters=2, random_state=32).fit(X_moons)

In [50]:
moons = pd.DataFrame(X_moons)

In [51]:
moons

            0         1
0    0.933909  0.351405
1    0.415411 -0.279095
2   -0.698502  0.658939
3    0.539620 -0.347504
4   -0.635103  0.806547
..        ...       ...
495  1.102930 -0.498893
496  0.287938 -0.208020
497  1.254352 -0.455151
498  0.804115  0.526129
499 -1.022368  0.432108

[500 rows x 2 columns]

In [52]:
kmeans.labels_

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1], dtype=int32)

In [53]:
results_df = pd.DataFrame({"x": X_moons[:, 0], "y": X_moons[:, 1], "cluster": kmeans.labels_})
px.scatter(results_df, x="x", y="y", color="cluster", title="K-Means Clustering Results")

In [54]:
kmeans.cluster_centers_

array([[ 1.1934597 , -0.07827812],
       [-0.20631631,  0.58666509]])

In [55]:
labels_DB = DBSCAN(eps=0.1).fit_predict(X_moons)
labels_df = pd.concat([results_df, pd.Series(labels_DB, name="DBSCAN")], axis=1)

In [56]:
results_df = pd.concat([results_df, pd.Series(labels_DB, name="DBSCAN")], axis=1)

In [57]:
results_df

            x         y  cluster  DBSCAN
0    0.933909  0.351405        0       0
1    0.415411 -0.279095        0       1
2   -0.698502  0.658939        1       0
3    0.539620 -0.347504        0       1
4   -0.635103  0.806547        1       0
..        ...       ...      ...     ...
495  1.102930 -0.498893        0       1
496  0.287938 -0.208020        0       1
497  1.254352 -0.455151        0       1
498  0.804115  0.526129        0       0
499 -1.022368  0.432108        1       0

[500 rows x 4 columns]

In [58]:
px.scatter(results_df, x="x", y="y", color="DBSCAN", title="DBSCAN Clustering Results")